export const GRID_MIN_HEIGHT_WHEN_AUTO = 8000; // px
export const GRID_HEIGHT_MULTIPLIER_WHEN_AUTO = 1.5;
export const ROWS_MIN_COUNT_WHEN_AUTO = 10000; // count
export const WATCH_ELEMENTS_HEIGHT_DELAY = 1000; // ms
export const WATCH_ELEMENTS_NOT_ORGANIZED_DELAY = WATCH_ELEMENTS_HEIGHT_DELAY * 2; // ms
